### ISSUE TITLE
Exception on shutdown if config.toml is incorrect

### ISSUE THREAD

**Issue by s-allius** [s-allius/tsun-gen3-proxy#125]
When I first time run preview.2, without correct config.toml and mqtt configuration is throws the below error. Once I placed config.toml and restartet the container it did no appear again. Will run the new version for a couple of hours and provide feedback.

'2024-07-11 08:17:44  INFO | root | Event loop is stopped'
'2024-07-11 08:17:44  INFO | root | Close MQTT Task'
Traceback (most recent call last):
  File "/home/tsun-proxy/mqtt.py", line 69, in __loop
    async with self.__client:
  File "/usr/local/lib/python3.12/site-packages/aiomqtt/client.py", line 703, in __aenter__
    raise MqttError(str(exc)) from None
aiomqtt.exceptions.MqttError: [Errno -2] Name does not resolve
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/tsun-proxy/./server.py", line 205, in <module>
    Inverter.class_close(loop)
  File "/home/tsun-proxy/inverter.py", line 78, in class_close
    loop.run_until_complete(cls.mqtt.close())
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/tsun-proxy/mqtt.py", line 40, in close
    await self.task
  File "/home/tsun-proxy/mqtt.py", line 118, in __loop
    await asyncio.sleep(interval)
  File "/usr/local/lib/python3.12/asyncio/tasks.py", line 665, in sleep
    return await future
           ^^^^^^^^^^^^
asyncio.exceptions.CancelledError

_Originally posted by @Timurling in https://github.com/s-allius/tsun-gen3-proxy/discussions/113#discussioncomment-10017216_

**Comment by s-allius** [comment]
fixed with #127
