### ISSUE TITLE
HA supervisor crashes on add-on reboots if add-on watchdog is in use 

### ISSUE THREAD

**Issue by s-allius** [s-allius/tsun-gen3-proxy#249]
If in the `config.yaml` we add the line

```yaml
watchdog: "http://[HOST]:[PORT:8127]/-/healthy"
```

we see on a add-on restart an exception like this:

```log
2024-12-15 20:24:46.863 INFO (SyncWorker_1) [supervisor.docker.manager] Stopping addon_local_tsun-proxy application
2024-12-15 20:24:50.483 INFO (SyncWorker_1) [supervisor.docker.manager] Cleaning addon_local_tsun-proxy application
2024-12-15 20:24:50.496 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-14254838' coro=<Addon.watchdog_container() done, defined at /usr/src/supervisor/supervisor/addons/addon.py:1491> exception=AddonsJobError('Rate limit exceeded, more than 10 calls in 0:30:00')>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/addons/addon.py", line 1505, in watchdog_container
    await self._restart_after_problem(event.state)
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 291, in wrapper
    raise on_condition(
supervisor.exceptions.AddonsJobError: Rate limit exceeded, more than 10 calls in 0:30:00
```
---

### Workaround: In version 0.12 we disabled the watchdog feature

**Comment by mime24** [comment]
issue seems solved with version 0.13 #291
