### ISSUE TITLE
Exception during parsing the contact info message

### ISSUE THREAD

**Issue by s-allius** [s-allius/tsun-gen3-proxy#33]
The following exceptions occur with the current main branch:

```
'2023-12-24 11:03:15 ERROR | conn | Exception for ('logger.talent-monitoring.com', 5005):
Traceback (most recent call last):
  File "/home/tsun-proxy/async_stream.py", line 31, in loop
    await self.__async_read()
  File "/home/tsun-proxy/async_stream.py", line 72, in __async_read
    self.read()                # call read in parent class
    ^^^^^^^^^^^
  File "/home/tsun-proxy/messages.py", line 164, in read
    self.__dispatch_msg()
  File "/home/tsun-proxy/messages.py", line 271, in __dispatch_msg

)
  File "/home/tsun-proxy/messages.py", line 288, in msg_contact_info
    self.__process_contact_info()
  File "/home/tsun-proxy/messages.py", line 302, in __process_contact_info
    result = struct.unpack_from(f'!{name_len+1}pB', self._recv_buffer,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
struct.error: unpack_from requires a buffer of at least 26 bytes for unpacking 3 bytes at offset 23 (actual buffer size is 24)
'
'2023-12-24 11:03:15 DEBUG | conn | in AsyncStream.close() l('172.28.1.32', 40620) | r('47.254.132.252', 5005)'
```

**Comment by s-allius** [comment]
Fixed with version 0.5.5
